### ISSUE TITLE
Add alchemy api option similar to sales bot

### ISSUE THREAD

**Issue by noob04coder** [kenryu42/nft-listing-monitor-bot#1]
Hello I love the work you are doing is it possible for you to replace the opensea and x2y2 api keys with alchemy as they are very difficult to get ,alchemy api option which you have recently added in your sales bot https://github.com/kenryu42/ethereum-nft-sales-bot

**Comment by kenryu42** [comment]
> Hello I love the work you are doing is it possible for you to replace the opensea and x2y2 api keys with alchemy as they are very difficult to get ,alchemy api option which you have recently added in your sales bot https://github.com/kenryu42/ethereum-nft-sales-bot

Listing on a marketplace is an off-chain activity. The Alchemy API does not work for it.
